### ISSUE TITLE
Is GELF::Notifier thread safe?

### ISSUE THREAD

**Issue by defsprite** [graylog-labs/gelf-rb#48]
I'm using a shared instance of `GELF::Notifier` in a preforked, threading server (puma), but looking at https://github.com/Graylog2/gelf-rb/blob/master/lib/gelf/notifier.rb#L155 I have noticed that the construction of the payload works via the instance variable `@hash`

Is this approach thread safe?

Shouldn't we mimic the approach taken in `GELF::Transport::UDP` and make the hash thread local or refactor to pass the resulting hash from method to method?

**Comment by milgner** [comment]
Yes, this is something that has been bothering me as well and is on my list of to-dos for this project. But feel free to submit a pull request, I'll gladly incorporate it!

**Comment by milgner** [comment]
My bad, I just realized that this is the issue for #49. Closing it in favour of the PR ticket :)

**Comment by defsprite** [comment]
Closing this as #49 has been merged long time ago.
