### ISSUE TITLE
New version of gem with Ruby 2.4.x support

### ISSUE THREAD

**Issue by Kitton** [graylog-labs/gelf-rb#61]
It will be really nice to release a new version of gem with the latest commits included (https://github.com/graylog-labs/gelf-rb/pull/55).

**Comment by goya** [comment]
i hereby support this issue.

**Comment by tboyko** [comment]
@milgner Are you able to release a `3.0.1` or `3.1.0` of the gem? We'd like to eliminate the numerous warnings that this gem is currently producing in our environments.

**Comment by tboyko** [comment]
@tessie Can you assist with this?

**Comment by joschi** [comment]
@milgner and @tessie are the maintainers of this project and they can create a release if they think it's ready.

**Comment by milgner** [comment]
After merging many changes, I'd have liked to run the current master in a staging environment for a bit, logging to a real system before releasing a new version. I'll give it a try today, if no immediate problems pop up, I'll create a release over the weekend.

**Comment by joschi** [comment]
@milgner Maybe the other commenters here in this issue can help with testing if you release a beta/release candidate.

**Comment by yuri1969** [comment]
@milgner, @tessie Is there a roadmap update regarding the `3.0.0+` release? Although many important PRs have been merged, we are still stuck with the almost 2 yo release. It'd be cool to have a fresh version available.

**Comment by tboyko** [comment]
@milgner Are you able to share with us how the tests went? Can we expect an updated release soon?

**Comment by tboyko** [comment]
Paging @edmundoa @jalogisch @joschi @lennartkoopmann @AlekSi @bernd @milgner 

Apologies if this is considered poor etiquette, but we could really use some help/feedback here.

**Comment by milgner** [comment]
I haven't received any additional feedback and unfortunately the tests I could do were a bit limited. I propose releasing a RC version, then, even if you don't want to point your Gemfile to Github, you can already use the new features from an official gem version.

**Comment by alex-mohemian** [comment]
@milgner If you do that today, I can test it in a real environment today 👍 Desperately need this since we're just migrating some legacy code to newer Ruby+Rails.

**Comment by tessie** [comment]
@milgner  Do let me know if you need any help.

**Comment by milgner** [comment]
@alex-mohemian I pushed a new version tag this morning but so far it doesn't seem to have been picked up by the release automatism. Currently busy on my day job and don't know whether I'll find some time this evening.

@tessie if you could find some time to check out why pushing the tag did not result in a new version being published, that would be really great!

**Comment by tessie** [comment]
Sure
Would check

**Comment by alex-mohemian** [comment]
@milgner is there a `3.1.0` release planned any time soon?

**Comment by milgner** [comment]
@alex-mohemian I did publish a tag for a release a couple of weeks ago but somehow it wasn't published correctly. I'll have to check the configuration again, something seems to be broken in the publishing process.

**Comment by alex-mohemian** [comment]
@milgner the `v3.1.0-rc.1` tag and subsequent gem is released correctly -- thank you for that. I was talking about a `3.1.0` GM/final/no-rc release 😉

**Comment by milgner** [comment]
@alex-mohemian ah, that is good to know. I was going by the information on [rubygems.org](https://rubygems.org/gems/gelf) which still shows `3.1.0.pre.rc.1` as the last version and so I thought that something was broken :grimacing: 
But seeing as no new issues have been opened since, I think we're good to go for a final release :tada: I'll schedule it for the next couple of days :+1:

**Comment by alex-mohemian** [comment]
I'm sorry, my mistake. Yes, `3.1.0.pre.rc.1` is the last version on rubygems.org.

**Comment by alex-mohemian** [comment]
@milgner Is there anything I could do to help you get the `3.1` out? 🙂

**Comment by milgner** [comment]
Since I'm not sure what the actual problem was, I'll go ahead and push another tag for 3.1 and see what happens. There might have been a problem with the version ordering among `3.1.0.pre.rc.1` and `3.1.0-rc.1` - but `3.1.0` might still work. 
In case the release doesn't show up at `rubygems.org`, I'll have to contact the Graylog team as they originally set up the auto-release process and I don't have access to that part of the configuration. For now, let's cross our fingers and hope that it will work :crossed_fingers:

**Comment by alex-mohemian** [comment]
@milgner looks like it did work :) [Rubygems](https://rubygems.org/gems/gelf) picked it up! Thank you!

**Comment by milgner** [comment]
@alex-mohemian that's great to hear! I struggled a bit with the old jeweler version not being able to regularly bump the version. @tessie already prepared a dependency version bump in #66 but unfortunately new versions of jeweler break compatibility with old Rubies... :grimacing: 
Nonetheless, closing this issue for now, as 3.1 has been released successfully :wink:
